name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@f3f4f0a0c4779a22f6d114cbf5fa039d0a863147
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_REPO: ForgeGuard/vuepress
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm i && npm run build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://www.forgeguard.net
