name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@1.8.0
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: ForgeGuard/vuepress
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: npm i && npm run build
        BUILD_DIR: docs/.vuepress/dist
        CNAME: https://forgeguard.net
